export const weatherStatusMap = {
    0:    { status: 'Čisto nebo',                                 image: '/res/sunny.svg' },
    1:    { status: 'Uglavnom čisto',                             image: '/res/cloudy.svg' },
    2:    { status: 'Delimično oblačno',                          image: '/res/cloudy.svg' },
    3:    { status: 'Oblačno',                                    image: '/res/cloudy.svg' },
    45:   { status: 'Maglovito',                                  image: '/res/fog.svg' },
    48:   { status: 'Maglovito',                                  image: '/res/fog.svg' },
    51:   { status: 'Sitna kisa',                                 image: '/res/drizzle.svg' },
    53:   { status: 'Sitna kisa',                                 image: '/res/drizzle.svg' },
    55:   { status: 'Sitna kisa',                                 image: '/res/drizzle.svg' },
    56:   { status: 'Sitna kisa',                                 image: '/res/drizzle.svg' },
    57:   { status: 'Sitna kisa',                                 image: '/res/drizzle.svg' },
    61:   { status: 'Kisa - Blag intenzitet',                     image: '/res/rain.svg' },
    63:   { status: 'Kisa - Umeren intenzitet',                   image: '/res/rain.svg' },
    65:   { status: 'Kisa - Jak intenzitet',                      image: '/res/extreme-rain.svg' },
    66:   { status: 'Ledena kisa - Lagan intenzitet',             image: '/res/sleet.svg' },
    67:   { status: 'Ledena kisa - Jak intenzitet',               image: '/res/sleet.svg' },
    71:   { status: 'Sneg',                                       image: '/res/snow.svg' },
    73:   { status: 'Sneg',                                       image: '/res/snow.svg' },
    75:   { status: 'Sneg',                                       image: '/res/snow.svg' },
    77:   { status: 'Sneg',                                       image: '/res/snow.svg' },
    80:   { status: 'Kišni pljuskovi - Blag intenzitet',          image: '/res/extreme-rain.svg' },
    81:   { status: 'Kišni pljuskovi - Umeren intenzitet',        image: '/res/extreme-rain.svg' },
    82:   { status: 'Kišni pljuskovi - Jak intenzitet',           image: '/res/extreme-rain.svg' },
    85:   { status: 'Snežni pljuskovi - Blag intenzitet',         image: '/res/extreme-snow.svg' },
    86:   { status: 'Snežni pljuskovi - Jak intenzitet',          image: '/res/extreme-snow.svg' },
    95:   { status: 'Grmljavina',                                 image: '/res/thunderstorms.svg' },
    96:   { status: 'Grmljavina',                                 image: '/res/thunderstorms.svg' },
    99:   { status: 'Grmljavina',                                 image: '/res/thunderstorms.svg' },
  };
  